### PR TITLE
Use networkFirst for samples & AMP Runtime

### LINKED ISSUE #599: ServiceWorker: Use networkFirst caching strategy for samples & AMP runtime
...to avoid problems like [this](https://github.com/ampproject/amphtml/issues/7296#issuecomment-277385399).

### PR DESCRIPTION
**Pull request by sebastianbenz**
Make sure page gets always the latest AMP Runtime and sample
code. Also: cache all other requests for offline access.

Fixes #599

### CODE REVIEW

**Comment by sebastianbenz** [comment]
@kul3r4 PTAL

**Comment by kul3r4** [comment]
Fine for me. Now that we are using `return toolbox.cacheFirst(request, values)` for the `if` and `else` (line 112, 121), would it be possible to remove the `else` and just have in the `if` the code about placeholder images?

**Comment by sebastianbenz** [comment]
The difference in the two branches is the image fallback. Or did I
misunderstood your suggestion?

**Comment by kul3r4** [comment]
LGTM

**Pull request merged**
