### PR TITLE
easier backend dev setup

### LINKED ISSUE #501: Can't get amp-list sample to run on localhost
Experiencing this regression on Goobuntu with node v5.5.0 and on Ubuntu 16.04 with node v7.2.0.
Also reported by a partner as a CORS issue blocking the sample from working locally.

Repro steps:

1. Clone the repo, cd, `npm install`
2. `gulp build`
3. `gulp backend:serve`
4. #ensure go_appengine is in $PATH
5. Navigate to http://localhost:8080. Notice the service worker failing to load.
6. Click the `amp-list` sample.

Error messages in the browser console:

```
amp.js:106Powered by AMP ⚡ HTML – Version 1478801557976 http://localhost:8080/components/amp-list/
2016-11-30 20:14:56.005 helpers.js:25[sw-toolbox] install event fired
2016-11-30 20:14:56.010 helpers.js:25[sw-toolbox] creating cache [$$$toolbox-cache$$$http://localhost:8080/$$$$$$inactive$$$]
2016-11-30 20:14:56.014 helpers.js:25[sw-toolbox] preCache list: /, /components/amp-img/, /components/amp-install-serviceworker/, /youre_offline/, /img/offline.png, /img/logo.svg, /favicons/favicon.ico, /favicons/favicon-230x230.png, /favicons/favicon-96x96.png, /favicons/android-chrome-36x36.png, /favicons/android-chrome-72x72.png, /img/ic_experiment_black_2x_web_18dp.png, /img/ic_experiment_black_1x_web_18dp.png, /img/ic_experiment_black_2x_web_24dp.png, /img/ic_experiment_black_1x_web_24dp.png, /img/ic_experiment_black_2x_web_36dp.png, /img/ic_experiment_black_1x_web_36dp.png, /img/ic_link_black_1x_web_18dp.png, /img/ic_link_black_2x_web_18dp.png, /img/ic_menu_white_1x_web_24dp.png, /img/ic_menu_white_2x_web_24dp.png, /img/ic_indeterminate_check_box_black_24dp_1x.png, /img/ic_indeterminate_check_box_black_24dp_2x.png, /img/ic_add_box_black_24dp_1x.png, /img/ic_add_box_black_24dp_2x.png, /img/ic_chevron_left_black_24dp_1x.png, /img/ic_chevron_left_black_24dp_2x.png, /img/ic_play_arrow_white_1x_web_24dp.png, /img/ic_play_arrow_white_2x_web_24dp.png, /img/ic_play_circle_filled_white_24dp_1x.png, /img/ic_play_circle_filled_white_24dp_2x.png, /img/GitHub-Mark-Light-32px.png, /img/GitHub-Mark-Light-64px.png, /img/abe_device_screenshot_1x.png, /img/abe_device_screenshot_2x.png
2016-11-30 20:14:56.136 http://localhost:8080/favicons/favicon.ico Failed to load resource: the server responded with a status of 404 (Not Found)
2016-11-30 20:14:56.136 http://localhost:8080/favicons/favicon-230x230.png Failed to load resource: the server responded with a status of 404 (Not Found)
2016-11-30 20:14:56.147 http://localhost:8080/favicons/favicon-96x96.png Failed to load resource: the server responded with a status of 404 (Not Found)
2016-11-30 20:14:56.159 http://localhost:8080/favicons/android-chrome-36x36.png Failed to load resource: the server responded with a status of 404 (Not Found)
2016-11-30 20:14:56.160 http://localhost:8080/favicons/android-chrome-72x72.png Failed to load resource: the server responded with a status of 404 (Not Found)
2016-11-30 20:14:56.289 localhost/:1 Fetch API cannot load https://ampbyexample.com/json/examples.json?__amp_source_origin=http%3A%2F%2Flocalhost%3A8080. The 'Access-Control-Allow-Origin' header has a value 'https://cdn.ampproject.org' that is not equal to the supplied origin. Origin 'http://localhost:8080' is therefore not allowed access. Have the server send the header with a valid value, or, if an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
2016-11-30 20:14:56.291 error.js:78 Fetch failed  https://ampbyexample.com/json/examples.json?__amp_source_origin=http%3A%2F%2Flocalhost%3A8080 : Failed to fetchmd @ error.js:78
2016-11-30 20:14:56.295 localhost/:1 Fetch API cannot load https://ampbyexample.com/json/examples.json?__amp_source_origin=http%3A%2F%2Flocalhost%3A8080. The 'Access-Control-Allow-Origin' header has a value 'https://cdn.ampproject.org' that is not equal to the supplied origin. Origin 'http://localhost:8080' is therefore not allowed access. Have the server send the header with a valid value, or, if an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
2016-11-30 20:14:56.296 error.js:78 Fetch failed  https://ampbyexample.com/json/examples.json?__amp_source_origin=http%3A%2F%2Flocalhost%3A8080 : Failed to fetchmd @ error.js:78
2016-11-30 20:14:56.298 localhost/:1 Fetch API cannot load https://ampbyexample.com/json/examples.json?__amp_source_origin=http%3A%2F%2Flocalhost%3A8080. The 'Access-Control-Allow-Origin' header has a value 'https://cdn.ampproject.org' that is not equal to the supplied origin. Origin 'http://localhost:8080' is therefore not allowed access. Have the server send the header with a valid value, or, if an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
2016-11-30 20:14:56.298 error.js:78 Fetch failed  https://ampbyexample.com/json/examples.json?__amp_source_origin=http%3A%2F%2Flocalhost%3A8080 : Failed to fetchmd @ error.js:78
2016-11-30 20:14:56.460 sw.js:1 Uncaught (in promise) TypeError: Request failed
2016-11-30 20:15:07.353 localhost/:1 Site cannot be installed: no matching service worker detected. You may need to reload the page, or check that the service worker for the current page also controls the start URL from the manifest
2016-11-30 20:15:55.823 sw.js:1 Service Worker termination by a timeout timer was canceled because DevTools is attached.
```

image

### PR DESCRIPTION
**Pull request by sebastianbenz**
* don't restrict CORS access to cdn.ampproject.org
* set backend endpoint in backend:serve instead of backend:watch
* migrate to gulp-run instead of gulp-shell which is not flexible enough

Fixes #501

### CODE REVIEW

**Comment by sebastianbenz** [comment]
@dandv FYI

**Comment by dandv** [comment]
After `git checkout backend-run`, `npm install`, `gulp build` and `gulp serve`, http://localhost:8080/components/amp-list/ returns the same errors:

image

**Comment by sebastianbenz** [comment]
The problem is this only works in watch mode -> the build runs before the host variable is set in serve.

**Comment by dandv** [comment]
Indeed, `gulp backend:serve` doesn't solve the problem.

However, [`gulp backend:watch`](https://github.com/ampproject/amp-by-example/blob/backend-run/gulpfile.js#L336) doesn't run the server:

```
➜  amp-by-example git:(backend-run) ✗ gulp backend:watch
[13:30:22] Using gulpfile ~/prg/3/amp-by-example/gulpfile.js
[13:30:22] Starting 'backend:watch'...
[13:30:22] Starting 'bower'...
[13:30:22] Using cwd: /usr/local/google/home/dandv/prg/3/amp-by-example
[13:30:22] Using bower dir: dist/bower_components
[13:30:22] Starting 'copy:images'...
[13:30:22] Starting 'copy:videos'...
[13:30:22] Starting 'copy:json'...
[13:30:22] Starting 'copy:fonts'...
[13:30:22] Starting 'copy:scripts'...
[13:30:22] Starting 'copy:license'...
[13:30:22] Starting 'copy:static'...
[13:30:22] Starting 'compile:favicons'...
[13:30:22] Starting 'compile:sitemap'...
[13:30:22] Starting 'compile:example'...
[13:30:22] Starting 'copy:well-known'...
[13:30:22] Finished 'copy:scripts' after 204 ms
[13:30:22] Finished 'copy:license' after 598 ms
[13:30:22] Finished 'copy:well-known' after 427 ms
[13:30:22] Finished 'copy:fonts' after 601 ms
[13:30:23] Finished 'copy:videos' after 689 ms
[13:30:23] Finished 'copy:json' after 893 ms
[13:30:23] Finished 'copy:static' after 1.03 s
[13:30:30] [TypeError: Buffer.alloc is not a function]
[13:30:31] Generated index.html
[13:30:31] Generated sitemap.json
[13:30:31] Generated introduction/hello_world/index.html
[13:30:31] Generated introduction/hello_world/embed/index.html
[13:30:31] Generated introduction/how_to_publish_amps/index.html
[13:30:31] Generated introduction/how_to_publish_amps/embed/index.html
[13:30:31] Generated components/amp-access/index.html
[13:30:31] Generated components/amp-access/embed/index.html
[13:30:31] Generated components/amp-accordion/index.html
[13:30:31] Generated components/amp-accordion/embed/index.html
[13:30:31] Generated components/amp-ad/index.html
[13:30:31] Generated components/amp-ad/embed/index.html
[13:30:31] Generated components/amp-analytics/index.html
[13:30:31] Generated components/amp-analytics/embed/index.html
[13:30:31] Generated components/amp-anim/index.html
[13:30:31] Generated components/amp-anim/embed/index.html
[13:30:31] Generated components/amp-app-banner/index.html
[13:30:31] Generated components/amp-app-banner/embed/index.html
[13:30:31] Generated components/amp-audio/index.html
[13:30:31] Generated components/amp-audio/embed/index.html
[13:30:31] Generated components/amp-brid-player/index.html
[13:30:31] Generated components/amp-brid-player/embed/index.html
[13:30:31] Generated components/amp-brightcove/index.html
[13:30:31] Generated components/amp-brightcove/embed/index.html
[13:30:31] Generated components/amp-carousel/index.html
[13:30:31] Generated components/amp-carousel/embed/index.html
[13:30:31] Generated components/amp-dailymotion/index.html
[13:30:31] Generated components/amp-dailymotion/embed/index.html
[13:30:31] Generated components/amp-experiment/index.html
[13:30:31] Generated components/amp-experiment/embed/index.html
[13:30:31] Generated components/amp-facebook/index.html
[13:30:31] Generated components/amp-facebook/embed/index.html
[13:30:31] Generated components/amp-font/index.html
[13:30:31] Generated components/amp-font/embed/index.html
[13:30:31] Generated components/amp-form/index.html
[13:30:31] Generated components/amp-form/embed/index.html
[13:30:31] Generated components/amp-form/preview/index.html
[13:30:31] Generated components/amp-form/preview/embed/index.html
[13:30:31] Generated components/amp-fx-flying-carpet/index.html
[13:30:31] Generated components/amp-fx-flying-carpet/embed/index.html
[13:30:31] Generated components/amp-gfycat/index.html
[13:30:31] Generated components/amp-gfycat/embed/index.html
[13:30:31] Generated components/amp-google-vrview-image/index.html
[13:30:31] Generated components/amp-google-vrview-image/embed/index.html
[13:30:31] Generated components/amp-google-vrview-image/preview/index.html
[13:30:31] Generated components/amp-google-vrview-image/preview/embed/index.html
[13:30:31] Generated components/amp-iframe/index.html
[13:30:31] Generated components/amp-iframe/embed/index.html
[13:30:31] Generated components/amp-image-lightbox/index.html
[13:30:31] Generated components/amp-image-lightbox/embed/index.html
[13:30:31] Generated components/amp-img/index.html
[13:30:31] Generated components/amp-img/embed/index.html
[13:30:31] Generated components/amp-instagram/index.html
[13:30:31] Generated components/amp-instagram/embed/index.html
[13:30:31] Generated components/amp-install-serviceworker/index.html
[13:30:31] Generated components/amp-install-serviceworker/embed/index.html
[13:30:31] Generated components/amp-jwplayer/index.html
[13:30:31] Generated components/amp-jwplayer/embed/index.html
[13:30:31] Generated components/amp-kaltura-player/index.html
[13:30:31] Generated components/amp-kaltura-player/embed/index.html
[13:30:31] Generated components/amp-lightbox/index.html
[13:30:31] Generated components/amp-lightbox/embed/index.html
[13:30:31] Generated components/amp-list/index.html
[13:30:31] Generated components/amp-list/embed/index.html
[13:30:31] Generated components/amp-live-list/index.html
[13:30:31] Generated components/amp-live-list/embed/index.html
[13:30:31] Generated components/amp-o2-player/index.html
[13:30:31] Generated components/amp-o2-player/embed/index.html
[13:30:31] Generated components/amp-pinterest/index.html
[13:30:31] Generated components/amp-pinterest/embed/index.html
[13:30:31] Generated components/amp-reach-player/index.html
[13:30:31] Generated components/amp-reach-player/embed/index.html
[13:30:31] Generated components/amp-sidebar/index.html
[13:30:31] Generated components/amp-sidebar/embed/index.html
[13:30:31] Generated components/amp-social-share/index.html
[13:30:31] Generated components/amp-social-share/embed/index.html
[13:30:31] Generated components/amp-soundcloud/index.html
[13:30:31] Generated components/amp-soundcloud/embed/index.html
[13:30:31] Generated components/amp-springboard-player/index.html
[13:30:31] Generated components/amp-springboard-player/embed/index.html
[13:30:31] Generated components/amp-sticky-ad/index.html
[13:30:31] Generated components/amp-sticky-ad/embed/index.html
[13:30:31] Generated components/amp-twitter/index.html
[13:30:31] Generated components/amp-twitter/embed/index.html
[13:30:31] Generated components/amp-user-notification/index.html
[13:30:31] Generated components/amp-user-notification/embed/index.html
[13:30:31] Generated components/amp-video/index.html
[13:30:31] Generated components/amp-video/embed/index.html
[13:30:31] Generated components/amp-vimeo/index.html
[13:30:31] Generated components/amp-vimeo/embed/index.html
[13:30:31] Generated components/amp-vine/index.html
[13:30:31] Generated components/amp-vine/embed/index.html
[13:30:31] Generated components/amp-youtube/index.html
[13:30:31] Generated components/amp-youtube/embed/index.html
[13:30:31] Generated advanced/amp-user-notification_with_server_endpoint/index.html
[13:30:31] Generated advanced/amp-user-notification_with_server_endpoint/embed/index.html
[13:30:31] Generated advanced/how_to_create_interactive_amp_pages/index.html
[13:30:31] Generated advanced/how_to_create_interactive_amp_pages/embed/index.html
[13:30:31] Generated advanced/how_to_create_interactive_amp_pages/preview/index.html
[13:30:31] Generated advanced/how_to_create_interactive_amp_pages/preview/embed/index.html
[13:30:31] Generated advanced/image_galleries_with_amp-carousel/index.html
[13:30:31] Generated advanced/image_galleries_with_amp-carousel/embed/index.html
[13:30:31] Generated advanced/integrating_videos_in_amp_an_overview/index.html
[13:30:31] Generated advanced/integrating_videos_in_amp_an_overview/embed/index.html
[13:30:31] Generated advanced/integrating_videos_in_amp_an_overview/preview/index.html
[13:30:31] Generated advanced/integrating_videos_in_amp_an_overview/preview/embed/index.html
[13:30:31] Generated advanced/long_list_of_amp-instagram_embeds/index.html
[13:30:31] Generated advanced/long_list_of_amp-instagram_embeds/embed/index.html
[13:30:31] Generated advanced/using_the_amp_url_api/index.html
[13:30:31] Generated advanced/using_the_amp_url_api/embed/index.html
[13:30:31] Generated advanced/using_the_google_amp_cache/index.html
[13:30:31] Generated advanced/using_the_google_amp_cache/embed/index.html
[13:30:32] Generated advanced/video_carousels_with_amp-carousel/index.html
[13:30:32] Generated advanced/video_carousels_with_amp-carousel/embed/index.html
[13:30:32] Generated samples_templates/comment_section/index.html
[13:30:32] Generated samples_templates/comment_section/embed/index.html
[13:30:32] Generated samples_templates/comment_section/preview/index.html
[13:30:32] Generated samples_templates/comment_section/preview/embed/index.html
[13:30:32] Generated samples_templates/hotel/index.html
[13:30:32] Generated samples_templates/hotel/embed/index.html
[13:30:32] Generated samples_templates/hotel/preview/index.html
[13:30:32] Generated samples_templates/hotel/preview/embed/index.html
[13:30:32] Generated samples_templates/housing/index.html
[13:30:32] Generated samples_templates/housing/embed/index.html
[13:30:32] Generated samples_templates/housing/preview/index.html
[13:30:32] Generated samples_templates/housing/preview/embed/index.html
[13:30:32] Generated samples_templates/live_blog/index.html
[13:30:32] Generated samples_templates/live_blog/embed/index.html
[13:30:32] Generated samples_templates/live_blog/preview/index.html
[13:30:32] Generated samples_templates/live_blog/preview/embed/index.html
[13:30:32] Generated samples_templates/news_article/index.html
[13:30:32] Generated samples_templates/news_article/embed/index.html
[13:30:32] Generated samples_templates/news_article/preview/index.html
[13:30:32] Generated samples_templates/news_article/preview/embed/index.html
[13:30:32] Generated samples_templates/product_listing/index.html
[13:30:32] Generated samples_templates/product_listing/embed/index.html
[13:30:32] Generated samples_templates/product_listing/preview/index.html
[13:30:32] Generated samples_templates/product_listing/preview/embed/index.html
[13:30:32] Generated samples_templates/product/index.html
[13:30:32] Generated samples_templates/product/embed/index.html
[13:30:32] Generated samples_templates/product/preview/index.html
[13:30:32] Generated samples_templates/product/preview/embed/index.html
[13:30:32] Generated samples_templates/recipe/index.html
[13:30:32] Generated samples_templates/recipe/embed/index.html
[13:30:32] Generated samples_templates/recipe/preview/index.html
[13:30:32] Generated samples_templates/recipe/preview/embed/index.html
[13:30:32] Generated amp_for_ads_a4a/a4a_banner_ad/index.html
[13:30:32] Generated amp_for_ads_a4a/a4a_banner_ad/embed/index.html
[13:30:32] Generated api/dist/amp_for_ads_a4a/a4a_banner_ad/index.html
[13:30:32] Generated amp_for_ads_a4a/a4a_banner_ad/preview/index.html
[13:30:32] Generated amp_for_ads_a4a/a4a_banner_ad/preview/embed/index.html
[13:30:32] Generated amp_for_ads_a4a/a4a_carousel/index.html
[13:30:32] Generated amp_for_ads_a4a/a4a_carousel/embed/index.html
[13:30:32] Generated api/dist/amp_for_ads_a4a/a4a_carousel/index.html
[13:30:32] Generated amp_for_ads_a4a/a4a_carousel/preview/index.html
[13:30:32] Generated amp_for_ads_a4a/a4a_carousel/preview/embed/index.html
[13:30:32] Generated amp-form-input-text-error/index.html
[13:30:32] Generated amp-form-input-text-error/embed/index.html
[13:30:32] Generated amp-form-input-text-success/index.html
[13:30:32] Generated amp-form-input-text-success/embed/index.html
[13:30:32] Generated amp-form-success/index.html
[13:30:32] Generated amp-form-success/embed/index.html
[13:30:32] Generated shopping_cart/index.html
[13:30:32] Generated shopping_cart/embed/index.html
[13:30:32] Generated test/index.html
[13:30:32] Generated test/embed/index.html
[13:30:32] Generated youre_offline/index.html
[13:30:32] Generated youre_offline/embed/index.html
[13:30:32] Generated sitemap.xml
[13:30:32] Finished 'compile:sitemap' after 9.91 s
[13:30:32] Finished 'bower' after 10 s
[13:30:32] Finished 'copy:images' after 10 s
[13:30:32] Finished 'compile:example' after 10 s
➜  amp-by-example git:(backend-run) ✗ echo $?
0
```

**Comment by sebastianbenz** [comment]
Fixed the problem that host is only set after the first build. 

@dandv @kul3r4 PTAL

**Comment by kul3r4** [comment]
This works for me (I don't have any errors) using gulp backend:watch, @dandv could you confirm as well?

**Pull request merged**
