### PR TITLE
New header design [do not merge yet]

### PR DESCRIPTION
**Pull request by sebastianbenz**
* collapse header on mobile devices
* add AMP logo
* introduce hamburger button (doesn't work yet)

[This](https://amp-by-example-staging.appspot.com) is what it looks like - I'm not sure yet about best background color for the header.

//cc @juliantoledo @kul3r4

### CODE REVIEW

**Comment by kul3r4** [comment]
Hi,
looks nice!
I tried the [link](https://amp-by-example-staging.appspot.com/):

1. When opening with responsive layout or Nexus 5x layout (with the Chrome console) and it doesn't scroll properly: the first lines are covered by the header.

2. When opening with responsive layout the header looks nicer than when opening with desktop: in fact, when opening with desktop, the hamburger, the logo, and the "view on github" button are not aligned. Is it done on purpose?

**Comment by sebastianbenz** [comment]
1. is fixed - forgot to change it for the index page.
2. I prefer the large logo on desktop as we have enough space. This gives us also the chance to add labels to the buttons. But your are right, the alignment is a bit off. I changed the logo to be centered. What do you think?

**Comment by kul3r4** [comment]
I think it looks better now, thanks for changing that.

**Comment by juliantoledo** [comment]
LGTM. I think the header's background looks good with that grey.
I will use this for the sidebar PR.

**Comment by sebastianbenz** [comment]
@juliantoledo can you please close this PR once you've cherry picked my commit.

**Comment by juliantoledo** [comment]
@sebastianbenz will do, thanks.

**Pull request closed without merging**
