### PR TITLE
replace mdl with ampstart

### PR DESCRIPTION
**Pull request by sebastianbenz**
* replaces material design lite lib with ampstart
* replaces h4 with h2 in docs (this was long overdue)
* provide a rough styling of doc headers and title

### CODE REVIEW

**Comment by sebastianbenz** [comment]
@kul3r4 it has begun... PTAL

**Comment by kul3r4** [comment]
Could you provide how it should look like for "provide a rough styling of doc headers and title"? Otherwise I am not sure what to check.

I noticed that, on the main page, content has no margin top.

contents

**Comment by sebastianbenz** [comment]
Everything needs to be restyled anyway so it doesn't really matter yet.

**Comment by kul3r4** [comment]
LGTM

**Pull request merged**
