### PR TITLE
AMP-Carousel with AMP-List

### PR DESCRIPTION
**Pull request by bthomas16**
Adding an advanced concept / endpoint so users can better understand how a dynamic carousel looks and works

### CODE REVIEW

**Comment by bthomas16** [comment]
I signed it!

**Comment by bthomas16** [comment]
I signed it!

**Comment by bthomas16** [comment]
I signed it!

**Comment by sebastianbenz** [comment]
Sorry for your troubles, can you make sure that your commit email address is the same you used for signing the CLA?

**Comment by bthomas16** [comment]
@sebastianbenz  I have made the edits in my latest commit

**Comment by bthomas16** [comment]
another bot check

**Comment by bthomas16** [comment]
last check, bot

**Comment by bthomas16** [comment]
last try

**Pull request closed without merging**
