### PR TITLE
add amp-accordion

### PR DESCRIPTION
**Pull request by sebastianbenz**
//cc @jkingyens this is an example for a component that won't validate as it is still in experimental.

### CODE REVIEW

**Comment by juliantoledo** [comment]
LGTM, just one detail, should we put (experimental) next to it, and any other, in the main page to highlight that fact?

**Comment by sebastianbenz** [comment]
I thought the same - what's a good way to mark examples as experimental?

**Comment by juliantoledo** [comment]
Maybe just a text next to them in the list (experimental: what does this mean?) with a link to https://github.com/ampproject/amphtml/tree/master/tools/experiments in the question.

**Comment by sebastianbenz** [comment]
but where do we add the flag when writing the sample?

**Comment by juliantoledo** [comment]
Would it be possible to read a <meta>? We can do it later in another pull.

**Pull request merged**
