### PR TITLE
Placeholder - Add selector keyboard

### PR DESCRIPTION
**Pull request by kul3r4**
This adds keyboard support for amp-selector, AMP code [here](https://github.com/ampproject/amphtml/pull/8835/files).
This is related to [https://github.com/ampproject/amphtml/issues/8992](https://github.com/ampproject/amphtml/issues/8992).
@aghassemi FYI

### CODE REVIEW

**Comment by aghassemi** [comment]
I actually recommend using `keyboard-select-mode="select"` for tabs . Also recommend waiting until validator changes role out before merging.

**Comment by kul3r4** [comment]
Thanks! I have updated it and we will wait until validator roll out.

**Comment by sebastianbenz** [comment]
@kul3r4 what's the status of this?

**Comment by kul3r4** [comment]
[https://github.com/ampproject/amphtml/pull/8835/files](https://github.com/ampproject/amphtml/pull/8835/files) which contains the validator  changes has been merged, I guess this is ready to go. Will take a look at the conflicts.

**Comment by kul3r4** [comment]
@sebastianbenz PTAL

**Pull request merged**
