### PR TITLE
Update AMP_for_E-Commerce_Getting_Started.html

### PR DESCRIPTION
**Pull request by dev7ch**
Suggestion for consistent text indention, due there have been little inconsistency

### CODE REVIEW

**Comment by kul3r4** [comment]
@dev7ch Thanks for your pull request, however it seems to me that the indentation is consinstent with other files like [https://github.com/ampproject/amp-by-example/blob/master/src/10_Introduction/_Hello_World.html](https://github.com/ampproject/amp-by-example/blob/master/src/10_Introduction/_Hello_World.html)

**Comment by dev7ch** [comment]
@kul3r4 do you want me to close this PR? ( i see, AMP is intended with 2 spaces every where)

**Comment by kul3r4** [comment]
@dev7ch if we are using 2 spaces everywhere I don't think we should change one file to 4, so I am in favour of closing it.

**Comment by dev7ch** [comment]
sure, i ll close it, but you could may have a look screenshot, this show you what i meant and what is inconsistent.

btw. why do you use 2 Spaces in AMP?

**Pull request closed without merging**
