### PR TITLE
Add payment Request sample

### LINKED ISSUE #713: Example for PaymentRequestAPI using iframe
Something that illustrates what's enabled by https://github.com/ampproject/amphtml/issues/7623. Should also work through the Google Search viewer.

### PR DESCRIPTION
**Pull request by sebastianbenz**
Taking over @afitz0 PR #806 as I had to make some additional changes. 

Fixes #713

### CODE REVIEW

**Comment by sebastianbenz** [comment]
@afitz0 FYI

**Comment by sebastianbenz** [comment]
Demo: https://amp-by-example-staging.appspot.com/advanced/payments_in_amp/

**Comment by sebastianbenz** [comment]
@rudygalfi @ericlindley-g FYI

**Comment by kul3r4** [comment]
Given nothing happens visually when clicking on the button but it only prints in the console "Buying product Apple: 1" it may be worth mentioning to look at the console, otherwise someone can click it and don't understand what you are trying to demonstrate

**Comment by sebastianbenz** [comment]
@kul3r4 which browser did you use? There should be a popup in Chrome:

screen shot 2017-05-15 at 6 10 22 am

**Comment by kul3r4** [comment]
Chrome with the staging URL

**Comment by sebastianbenz** [comment]
Ah sorry - works now. Wasn't up-to-date.

**Comment by sebastianbenz** [comment]
Just made another small change to address Ade's comment. Button shows no a different value on safari.

**Comment by kul3r4** [comment]
Hi, I tried again on staging and the button is now not clickable.

**Pull request merged**
