### PR TITLE
Remove unused amp-sidebar

### PR DESCRIPTION
**Pull request by kul3r4**
Including unused libraries creates warnings, better to remove them.
@sebastianbenz PTAL

### CODE REVIEW

**Comment by sebastianbenz** [comment]
Afaik - the product sample uses a sidebar (see templates/product/header.html).

**Comment by kul3r4** [comment]
Right, it's imported. I think the problem is in the preview. I was looking at [product preview](https://ampbyexample.com/samples_templates/product/preview/). If you inspect the page, I can't find the amp-sidebar being used, and I can see the warning in the console.

**Comment by sebastianbenz** [comment]
This is actually a problem in the product sample: the sidebar should work.

**Comment by kul3r4** [comment]
We may need a way to remove the amp-sidebar import when building the preview page, as it doesn't have a menu and we are still importing the library.

**Comment by sebastianbenz** [comment]
Nope. The preview page should show the sidebar. It's defined in the sample source.

**Comment by kul3r4** [comment]
oh yes, you are right, it's there. However when I click on it I get:
Uncaught Error: Action Error: target not found in [tap:drawermenu.toggle]​​​
    at na.f.assert (log.js:285)
    at Uf (action-impl.js:286)
    at Kf.f.trigger (action-impl.js:270)
    at HTMLDocument.<anonymous> (action-impl.js:146)
sounds like this need more investigation.

**Comment by sebastianbenz** [comment]
Found the problem, this line `{{{elementsAfterBody}}}` needs to go directly after `<body>` in templates/preview.html.

**Comment by sebastianbenz** [comment]
Fixed it as part of #612

**Pull request closed without merging**
