### PR TITLE
Link to playground from homepage

### PR DESCRIPTION
**Pull request by sebastianbenz**

### CODE REVIEW

**Comment by sebastianbenz** [comment]
screen shot 2017-01-30 at 16 25 35

**Comment by kul3r4** [comment]
What about something on top of the page, similar to [ampproject](https://www.ampproject.org/) on top, where it says: "Save the date: Tune in live on March 7/8 or join us in person in NYC for our first-ever AMP Conf.". We could have one like: Try the new AMP playground

**Comment by sebastianbenz** [comment]
I've been looking for a good excuse to get rid of the device screenshot for a while now ;-)

**Comment by sebastianbenz** [comment]
Otherwise I'd preferred your suggestion ;-)/

**Comment by kul3r4** [comment]
LGTM as first step.

If possible, we should go back on restyling the main page. I suggest to remove the AMP logo from "Try the new..." as we have already a logo on top.

**Pull request merged**
