### PR TITLE
amp-fx-collection sample replacing amp-fx-parallax

### PR DESCRIPTION
**Pull request by aghassemi**
Not experimental but validation rules are not in prod yet, will remove the `"skipValidation": "true"` soon.

localhost_8000_components_amp-fx-collection_

### CODE REVIEW

**Comment by kul3r4** [comment]
Looks good! Only question from me is: should we mention that replaces the old component? Is the old one "deprecated"?

**Comment by aghassemi** [comment]
@kul3r4 yes and good idea to document. Added.
@sebastianbenz fixed. PTAL.

**Comment by sebastianbenz** [comment]
Thanks. Forgot one thing: can you please add a redirect:

"/components/amp-fx-parallax/": "/components/amp-fx-collection/"

to backend/redirects.json.

**Comment by aghassemi** [comment]
@sebastianbenz done. Nice feature BTW!

**Comment by sebastianbenz** [comment]
Cheers!

**Pull request merged**
