### PR TITLE
Add ABE for <amp-fx="fly-in">

### PR DESCRIPTION
**Pull request by nainar**
This PR does the following:
- Cleans up previous examples to follow pattern in demos on other ABEs
- Adds demos for `<amp-fx="fly-in">`
- Also adds demos on combining presets to make more complicated animations

### CODE REVIEW

**Comment by nainar** [comment]
@sebastianbenz sorry for the long PR. PTAL?

**Comment by kul3r4** [comment]
@nainar could you rebase from master for fixing the build issue? thanks!

**Comment by nainar** [comment]
@kul3r4 done!

**Comment by nainar** [comment]
No problem! :) thank you for taking a look!

**Pull request merged**
