### PR TITLE
Rename gcloud dependency to google-cloud

### PR DESCRIPTION
**Pull request by dandv**
Per https://github.com/GoogleCloudPlatform/google-cloud-node#where-did-gcloud-node-go

### CODE REVIEW

**Comment by sebastianbenz** [comment]
Hm - do we actually need this dependency?

**Comment by dandv** [comment]
Can we :cut: it?

**Comment by sebastianbenz** [comment]
yes please :-)

**Comment by sebastianbenz** [comment]
Fixed in 4c8edc1072dc2f6ffbefa31f9ce84786699c5c5e

**Pull request closed without merging**
