### PR TITLE
Rename product listing to browse page

### PR DESCRIPTION
**Pull request by kul3r4**
@sebastianbenz PTAL
@ericlindley-g FYI

### CODE REVIEW

**Comment by sebastianbenz** [comment]
please add a redirect here: https://github.com/ampproject/amp-by-example/blob/master/backend/redirects.json

**Comment by sebastianbenz** [comment]
Can we rename it to 'Product Browse Page'?

**Comment by kul3r4** [comment]
Done. @sebastianbenz PTAL

**Comment by kul3r4** [comment]
@sebastianbenz I renamed the product page as well.

**Pull request merged**
