### PR TITLE
New landing page design

### PR DESCRIPTION
**Pull request by sebastianbenz**
* New landing page design in theme colors
* Use cards for samples
* Give each sample section an introduction

This required:

* Add index.json file to each sample section with description
* Make sure that all samples have a proper introductory sentence
* Remove all HTML tags from description.
* Replace description extraction via regex with hand-written parser
* Update sw.js to precache new images
* ExampleFile#category() returns now an category object

### CODE REVIEW

**Comment by sebastianbenz** [comment]
@kul3r4 @juliantoledo PTAL

**Comment by kul3r4** [comment]
The bit I don't like is the title for each section on top of the cards (as [this)](https://www.dropbox.com/s/6rbz8t94je6swm0/cards-snapshot.png?dl=0)

**Comment by sebastianbenz** [comment]
Me neither. Also: using cards for each sample makes it hard to find samples. Maybe adding a listing of all samples with jumps to the cards could solves both problems...

**Comment by sebastianbenz** [comment]
[New version](https://dl.dropboxusercontent.com/u/7234606/index-cards-demo-landing-page-2.html.html):

* full responsive
* no more separate category pages

I like it - and it will work better if we have more categories with less samples.

screen shot 2016-07-03 at 12 04 31
screen shot 2016-07-03 at 12 04 20
screen shot 2016-07-03 at 12 04 05
screen shot 2016-07-03 at 12 03 56

**Comment by sebastianbenz** [comment]
I've updated the PR with a new version including various fixes and improvements. See it in action on [staging](https://amp-by-example-staging.appspot.com).

@kul3r4 @juliantoledo let me know what you think.

**Comment by kul3r4** [comment]
I really like it!

**Comment by sebastianbenz** [comment]
Small update:

* generate better descriptions for the sample cards
* magenta colored headline in landing page - thoughts?

**Comment by juliantoledo** [comment]
I really like it with this new format! great job! LGTM

**Comment by sebastianbenz** [comment]
New update:

* added description to all sections
* small footer tweaks
* add beaker icon to cards with experimental icon
* add experiment and highlight css class to cards for future styling
* add beaker icon to experimental cards

Open Questions:

* Please review the section descriptions
* Should we have a heading before the index in the landing page?
* Cards: better with or without border above the "view samples" action?
* Does the sample screenshot make sense in the landing page? Are there better ones?

**Comment by juliantoledo** [comment]
- Please review the section descriptions:
Many descriptions have components names and they are not treated the same way everywhere, some are just text "amp-lightbox", others are highlighted 'amp-list' and the rest are links on pink to the component page. They all should behave the same, I like the link, but maybe is confusing because it navigates away, so highlight seems better.

- Should we have a heading before the index in the landing page?
Do you mean the Contents with the 3 pink links? that could be a card.

- Cards: better with or without border above the "view samples" action? the line dividing seems good.

- Does the sample screenshot make sense in the landing page? Are there better ones? Maybe, but it would be difficult to build meaningful ones for every component that fits the cards.

**Comment by sebastianbenz** [comment]
@juliantoledo 

* Good point. Descriptions are generated from the samples (it's the first sentence). Hence we would need to change all samples first to have a consistent styling (it might make sense to add a link to the docs for the first occurrence of a component). I've disabled links and highlights for now - improves the readability of the cards.
* I'm not sure it makes sense to put the table of contents onto a card: it's not further content that is expanded. 
* Regarding screenshots: I only meant the device screenshot to the right of the introduction. Having screenshots for all samples doesn't make sense.

**Comment by sebastianbenz** [comment]
Updated the PR. It's now ready for review:

* New landing page design in theme colors
* Use cards for samples
* Give each sample section an introduction

This required:

* Add index.json file to each sample section with description
* Make sure that all samples have a proper introductory sentence
* Remove all HTML tags from description.
* Replace description extraction via regex with hand-written parser
* Update sw.js to precache new images
* ExampleFile#category() returns now an category object

@juliantoledo @kul3r4 please review

**Comment by kul3r4** [comment]
LGTM, once the build is fixed.

**Comment by sebastianbenz** [comment]
Fixed the build. PTAL

**Pull request merged**
