### PR TITLE
Remove experiment for amp-sidebar.html

### LINKED ISSUE #1053: [AMP Components in Firefox][NF]_[Components_amp sidebar] Enable experiment button is greyed out
Enable experiment button is greyed out in Components amp sidebar .Is this intended?
1.Go to https://ampbyexample.com/
2.Tap on Components
3.Tap on amp-sidebar and observe experiment button greyed out in experiment box
Observed result: Experiment button greyed out and non responsive
Expected results: Experiment button button should be responsive
Device(s):
Mac os desktop
Firefox :57.0.4 (64-bit)
Screenshot:https://screenshot.googleplex.com/kvAV901BCQS

### PR DESCRIPTION
**Pull request by kul3r4**
Fixes #1053

### CODE REVIEW

**Comment by kul3r4** [comment]
@sebastianbenz now I remember: we kept the experimental status to disable the validation because at the moment we have 2 `amp-sidebar` and that does not pass the validation, right?

**Comment by sebastianbenz** [comment]
There are already two PRs for this:
https://github.com/ampproject/amp-by-example/pull/956

**Comment by sebastianbenz** [comment]
Let's simply disable validation for this.

**Comment by kul3r4** [comment]
Agree, sorry for bringing it up again!

**Pull request closed without merging**
