### PR TITLE
Make code sections expandable

### PR DESCRIPTION
**Pull request by sebastianbenz**
Use a generic algorithm to collapse code sections. Collapse if:

- code section has no comment
- code section has > 4 lines

### CODE REVIEW

**Comment by sebastianbenz** [comment]
@kul3r4  PTAL

**Comment by sebastianbenz** [comment]
Preview is [here](https://amp-by-example-staging.appspot.com).

**Comment by sebastianbenz** [comment]
fixed validation errors

**Comment by kul3r4** [comment]
LGTM, as you are there, would you mind removing the comment for the css in the Housing sample? 
That would collapse that long section as well.

**Comment by sebastianbenz** [comment]
* Added tests
* Went through all samples and fixed the ones with an invalid formatting

**Comment by sebastianbenz** [comment]
@kul3r4 PTAL

**Comment by kul3r4** [comment]
LGTM

**Pull request merged**
