### PR TITLE
Don't cache sw.js

### PR DESCRIPTION
**Pull request by sebastianbenz**

### CODE REVIEW

**Comment by sebastianbenz** [comment]
I can't test this at the moment though.

**Comment by sebastianbenz** [comment]
@kul3r4 can you maybe try it on your machine? 

```
$ goapp serve
$ curl -I localhost:8080/sw/js | grep max-age # should have `max-age=0` set

**Comment by kul3r4** [comment]
It gives me 404

**Comment by sebastianbenz** [comment]
Did you run goapp serve?

**Comment by sebastianbenz** [comment]
This is what I'm seeing:

```
HTTP/1.1 200 OK
Content-length: 4727
Content-type: application/javascript
ETag: "MTg5NDc3NTc2NA=="
Expires: Fri, 01 Jan 1990 00:00:00 GMT
Cache-Control: no-cache
Access-Control-Allow-Origin: *
Server: Development/2.0
Date: Tue, 08 Nov 2016 13:12:23 GMT
```

**Comment by kul3r4** [comment]
This is what I get as well:

HTTP/1.1 200 OK
Content-length: 4727
Content-type: application/javascript
ETag: "MTg5NDc3NTc2NA=="
Expires: Fri, 01 Jan 1990 00:00:00 GMT
Cache-Control: no-cache
Access-Control-Allow-Origin: *
Server: Development/2.0
Date: Tue, 08 Nov 2016 16:27:01 GMT

LGTM

**Pull request merged**
