### PR TITLE
CSS fixes

### PR DESCRIPTION
**Pull request by sebastianbenz**
* rename generic highlighting class "warning" -> "important"
* fix padding around links in cards
* fix padding in previews for smaller screens (no more grey
  lines for empty previews
* fix margin for preview and code blocks for smaller screens

### CODE REVIEW

**Comment by sebastianbenz** [comment]
@kul3r4 @juliantoledo PTAL

**Comment by juliantoledo** [comment]
LGTM

**Comment by kul3r4** [comment]
Please apply the changes to the latest example added, amp-live-list.hml.

**Comment by sebastianbenz** [comment]
@kul3r4 PTAL

**Pull request merged**
