### PR TITLE
Uses different images

### PR DESCRIPTION
**Pull request by kul3r4**
Solves #407 
@sebastianbenz  PTAL

### CODE REVIEW

**Comment by kul3r4** [comment]
Images are under CC0, they don't require attribution.
I updated the other samples, yes the images have different resolutions, but the carousel still works.

**Comment by sebastianbenz** [comment]
Some of the images have way too much whitespace in the carousel due to different aspect ratios. Can you please only use images with roughly the same aspect ratio in the NewsArticle carousel. Thanks!

screen shot 2016-10-21 at 08 19 37

**Comment by kul3r4** [comment]
@sebastianbenz I picked other 2 images with more similar height.

**Comment by sebastianbenz** [comment]
LGTM - thanks for doing this!

**Comment by kul3r4** [comment]
@ericlindley-g FYI

**Comment by ericlindley-g** [comment]
Looks great—thank you!

**Pull request merged**
