### PR TITLE
setup redirects to amp.dev

### PR DESCRIPTION
**Pull request by sebastianbenz**

### CODE REVIEW

**Comment by sebastianbenz** [comment]
Tested against sitemap:

```
Failed redirects:  5
/introduction/amp_for_e-commerce_getting_started/ [INVALID REDIRECT TARGET]
/components/amp-addthis/ [INVALID REDIRECT TARGET]
/components/amp-springboard-player/ [INVALID REDIRECT TARGET]
/components/amp-web-push/ [INVALID REDIRECT TARGET]
/advanced/favorite_button/ [INVALID REDIRECT TARGET]
```

`amp_for_e-commerce_getting_started` -> ?

The other samples are marked as draft.

**Comment by matthiasrohmer** [comment]
Will fix up ampproject/docs#1767 now, then this should be good.

**Comment by sebastianbenz** [comment]
Verified that it works on staging: https://amp-by-example-staging.appspot.com

**Comment by sebastianbenz** [comment]
Added a few more fixes after testing the static redirects. These are still broken, but should be fixed with next amp.dev release.

```
Failed redirects:  44
/introduction/amp_for_e-commerce_getting_started/ [INVALID REDIRECT TARGET]
/components/amp-addthis/ [INVALID REDIRECT TARGET]
/advanced/favorite_button/ [INVALID REDIRECT TARGET]
/components/amp-springboard-player/ [INVALID REDIRECT TARGET]
/components/amp-web-push/ [INVALID REDIRECT TARGET]
/advanced/favorite_button/ [INVALID REDIRECT TARGET]
/components/amp-addthis/ [INVALID REDIRECT TARGET]
/components/amp-springboard-player/ [INVALID REDIRECT TARGET]
/components/amp-web-push/ [INVALID REDIRECT TARGET]
/introduction/amp_for_e-commerce_getting_started/ [INVALID REDIRECT TARGET]
/samples_templates/shopping_cart/preview/embed/ [INVALID REDIRECT TARGET]
/amp-app-banner-manifest.json [INVALID REDIRECT TARGET]
/amp4mail/gallery.html [INVALID REDIRECT TARGET]
/hreflang/fr/index.amp.html [INVALID REDIRECT TARGET]
/hreflang/fr/index.html [INVALID REDIRECT TARGET]
/hreflang/index.amp.html [INVALID REDIRECT TARGET]
/hreflang/index.html [INVALID REDIRECT TARGET]
/internationalization/alternate/fr/index.amp.html [INVALID REDIRECT TARGET]
/internationalization/alternate/fr/index.html [INVALID REDIRECT TARGET]
/internationalization/alternate/fr/index.mobile.html [INVALID REDIRECT TARGET]
/internationalization/alternate/index.amp.html [INVALID REDIRECT TARGET]
/internationalization/alternate/index.html [INVALID REDIRECT TARGET]
/internationalization/alternate/index.mobile.html [INVALID REDIRECT TARGET]
/internationalization/alternate/ja/index.amp.html [INVALID REDIRECT TARGET]
/internationalization/alternate/ja/index.html [INVALID REDIRECT TARGET]
/internationalization/alternate/ja/index.mobile.html [INVALID REDIRECT TARGET]
/internationalization/amp_hreflang_example_1.png [INVALID REDIRECT TARGET]
/internationalization/amp_hreflang_example_2.png [INVALID REDIRECT TARGET]
/internationalization/basic/fr/index.amp.html [INVALID REDIRECT TARGET]
/internationalization/basic/fr/index.html [INVALID REDIRECT TARGET]
/internationalization/basic/index.amp.html [INVALID REDIRECT TARGET]
/internationalization/basic/index.html [INVALID REDIRECT TARGET]
/internationalization/basic/ja/index.amp.html [INVALID REDIRECT TARGET]
/internationalization/basic/ja/index.html [INVALID REDIRECT TARGET]
/internationalization/rtl.html [INVALID REDIRECT TARGET]
/invalid_amp.html [INVALID REDIRECT TARGET]
/linker/demo-page.html [INVALID REDIRECT TARGET]
/linker/destination-page.html [INVALID REDIRECT TARGET]
/manifest.json [INVALID REDIRECT TARGET]
/sw.html [INVALID REDIRECT TARGET]
/sw.js [MISSING REDIRECT]
/webpush/amp-web-push-helper-frame.html [INVALID REDIRECT TARGET]
/webpush/amp-web-push-permission-dialog.html [INVALID REDIRECT TARGET]
/json/seatmap-neighbours.json [INVALID REDIRECT TARGET]
```

**Pull request merged**
