### PR TITLE
add sample for gallery with preview

### PR DESCRIPTION
**Pull request by sebastianbenz**

### CODE REVIEW

**Comment by sebastianbenz** [comment]
@camelburrito PTAL 

Previews: 

* https://amp-by-example-staging.appspot.com/advanced/image_galleries_with_amp-carousel/
* https://amp-by-example-staging.appspot.com/samples_templates/product/preview/

**Comment by sebastianbenz** [comment]
@kul3r4 PTAL

**Comment by sebastianbenz** [comment]
Samples here:

- https://amp-by-example-staging.appspot.com/advanced/image_galleries_with_amp-carousel/
- https://amp-by-example-staging.appspot.com/samples_templates/product/preview/

**Comment by kul3r4** [comment]
Regarding [product sample](https://amp-by-example-staging.appspot.com/samples_templates/product/preview/), whenever i click for adding to the shopping basket, nothing happens.

**Comment by kul3r4** [comment]
LGTM

**Pull request merged**
