### PR TITLE
fix amp list overflow

### PR DESCRIPTION
**Pull request by sebastianbenz**
* new button hasn't got enough space
* replace button with div to make it work

### CODE REVIEW

**Comment by sebastianbenz** [comment]
@kul3r4 PTAL

**Comment by kul3r4** [comment]
It is aligning on the right, is it correct? Wouldn't be better to be below the visible content?
Moreover, should we add some padding to the button?

**Comment by sebastianbenz** [comment]
Below doesn't really work as it'll interfere with the list content. You're
right about the margin.

**Comment by sebastianbenz** [comment]
Added margin. Fixed also that margins in preview didn't show.

**Comment by kul3r4** [comment]
I think the margin is not enough for the button and we would need padding This is what I see:
button

**Comment by sebastianbenz** [comment]
Sure? Works for me: https://amp-by-example-staging.appspot.com/components/amp-list/

**Comment by kul3r4** [comment]
ops sorry, probably I was looking at an old version of the page.
LGTM

**Pull request merged**
