### PR TITLE
remove sample amps from draft

### PR DESCRIPTION
**Pull request by sebastianbenz**
* fix header in newsarticle
* all samples use the same related articles
* fixed links for related articles

### CODE REVIEW

**Comment by sebastianbenz** [comment]
Publish the sample AMPs.

@borisf @dandv PTAL

**Comment by sebastianbenz** [comment]
Fixed related articles for product page.

**Comment by sebastianbenz** [comment]
@borisf @dandv please check if your samples still work as you intended before I publish them.

**Comment by dandv** [comment]
The Recipe sample works as - except it's not discoverable/clickable from `/`.

**Comment by sebastianbenz** [comment]
@dandv have you tried a clean build locally? It should show up.

**Comment by sebastianbenz** [comment]
@borisf can you please check your sample as well

**Pull request merged**
