### PR TITLE
Add demos for <amp-fx="fade-in-scroll">

### PR DESCRIPTION
**Pull request by nainar**
Demos for experimental fade-in-scroll

### CODE REVIEW

**Comment by nainar** [comment]
@sebastianbenz could you take a look?

Turns out last time fade-in-scroll hadn't made it to prod yet. Just checked https://cdn.ampproject.org/v0/amp-fx-collection-0.1.js and it has. Turns out last time I was being 🤦‍♀️ and didn't scroll far enough to the fade-in-scroll and experiments and was looking at the fade-in ones. :/

**Comment by devignerforhire** [comment]
Are these demos live yet? I checked the AMP by Example site, but couldn't see anything.

**Comment by sebastianbenz** [comment]
Yes, they're live here:
https://ampbyexample.com/components/amp-fx-collection/#scroll-dependent-fade-in

>

**Comment by devignerforhire** [comment]
Awesome, thank you Sebastian! Hope you're having a good weekend :)

**Pull request merged**
