### PR TITLE
Removing experimental tag for amp-social-share from samples

### PR DESCRIPTION
**Pull request by kul3r4**
Yesterday the tag experimental was removed from amp-social-share, reference [here](https://github.com/ampproject/amphtml/pull/3173)

### CODE REVIEW

**Comment by sebastianbenz** [comment]
The sample doesn't validate yet.

**Comment by kul3r4** [comment]
Right, the example needs to be updated, as in [here](https://github.com/ampproject/amphtml/commit/5585c2ec7a228dd18317803da0412c1a9e6d29f7) the way of passing parameters has changed, from json to the usage of data-param. I will take care of that.

**Comment by kul3r4** [comment]
Removed the json configuration, PTAL.

**Comment by sebastianbenz** [comment]
LGTM  - we should add samples for all supported share providers.

**Comment by kul3r4** [comment]
Ok, added gplus, email, pinterest.

**Comment by sebastianbenz** [comment]
Cool - you can find a facebook sample here: https://github.com/ampproject/amp-by-example/blob/master/src/50_Sample_AMPs/News_Article.html#L147

**Comment by kul3r4** [comment]
Missed that! Added it in the common usage section as it's using the attribution parameter.

**Comment by sebastianbenz** [comment]
Great! 

Oh - and we need to remove the experimental flag from the NewsArticle sample as well.

**Comment by kul3r4** [comment]
Ok, as I am here, can I remove the draft flag as well from the NewsArticle sample?

**Comment by sebastianbenz** [comment]
that'd make sen.

**Comment by kul3r4** [comment]
ok, all done.

**Comment by sebastianbenz** [comment]
I've noticed that the share icons are not all aligned on the same line. We could avoid this by wrapping all of them in a div:

```
<div>
  <amp-social-share type="twitter" width="60" height="44"> </amp-social-share>
   </amp-social-share>		 +  <amp-social-share type="gplus" width="60" height="44"></amp-social-share>
   <amp-social-share type="email" width="60" height="44"></amp-social-share>
   <amp-social-share type="pinterest" width="60" height="44"></amp-social-share>
</div>
```

**Comment by sebastianbenz** [comment]
Another thing: we should include facebook and linkedin in the first list as well. Mention in the docs that facebook requires in the data-attribution field the [facebook app id](https://developers.facebook.com/apps). 

...sorry for turning this PR into a bigger thing. We should also change the commit message.

**Comment by kul3r4** [comment]
All done.PTAL.

**Comment by sebastianbenz** [comment]
Facebook requires the app_id via attribution. I would remove the second sample and add the app_id value to the first sample. Move the explanation to the first sample. Thanks!

**Comment by kul3r4** [comment]
All done. PTAL.

**Comment by sebastianbenz** [comment]
please `"draft": true,` for NewsArticle. Otherwise LGTM

**Comment by sebastianbenz** [comment]
LGTM - thanks!

**Comment by sebastianbenz** [comment]
Merged. One comment: please try to keep the title of git commit messages < 50 chars ([more info](http://chris.beams.io/posts/git-commit/)).

**Pull request merged**
