### PR TITLE
Use hidden in with amp-bind instead of classes

### PR DESCRIPTION
**Pull request by kul3r4**
I made an attempt to improve the Product page code by using [hidden] in elements using amp-bind. I am not sure how to do with default values where I can't use hidden otherwise they will be hidden at default, so I think for those it's still worth using classes.
@sebastianbenz WDYT?

### CODE REVIEW

**Comment by sebastianbenz** [comment]
Have you got a sample for ' default values where I can't use hidden'?

**Comment by sebastianbenz** [comment]
I think you can replace it here `<ul class="show" [class]="product.selectedColor == 'green' ? 'show' : 'hide'">` as well.

...and here as well: [class] = "(product.hasMorePages == false ? 'hide' : 'ampstart-btn caps m1 mb3 show')">

**Comment by kul3r4** [comment]
@sebastianbenz you are right it works.
I was thinking that I would not be able to use `[hidden]` without `hidden` but it actually works, so the default, which is green and is visible at load, can just have `[hidden]` without `hidden`.

**Comment by sebastianbenz** [comment]
Does the fadein still work?

**Comment by kul3r4** [comment]
Yes

**Pull request merged**
