### PR TITLE
Link to official docs instead of Github. #394

### PR DESCRIPTION
**Pull request by sebastianbenz**

### CODE REVIEW

**Comment by sebastianbenz** [comment]
@kul3r4 PTAL

**Comment by kul3r4** [comment]
Hi, I think some are missing:
- [A4A_Banner_Ad](https://github.com/ampproject/amp-by-example/blob/3f774161d3764f2c6fe4ea4cda97cd0f96e2afd4/src/60_AMP_for_Ads_(A4A)/A4A_Banner_Ad.html) has still (this)[https://github.com/ampproject/amphtml/blob/master/builtins/amp-pixel.md] reference  (line 42) and [doc](https://www.ampproject.org/docs/reference/components/amp-pixel) could be used
- [amp-install-serviceworker](https://github.com/ampproject/amp-by-example/blob/3f774161d3764f2c6fe4ea4cda97cd0f96e2afd4/src/20_Components/amp-install-serviceworker.html) at line 7 could use the [doc](https://www.ampproject.org/docs/reference/components/amp-install-serviceworker)
- [amp-font](https://github.com/ampproject/amp-by-example/blob/3f774161d3764f2c6fe4ea4cda97cd0f96e2afd4/src/20_Components/amp-font.html) at line 17 could use [doc](https://www.ampproject.org/docs/reference/components/amp-font)

**Comment by sebastianbenz** [comment]
fixed - and some more references I've missed. PTAL

**Comment by kul3r4** [comment]
LGTM

**Pull request merged**
