### PR TITLE
add setting to skip validation. fail validation fails build.

### PR DESCRIPTION
**Pull request by jkingyens**
This adds a flag to skip validation. This is used to skip amp-list which currently exposes a validation bug right now.

### CODE REVIEW

**Comment by jkingyens** [comment]
I intentionally submitted PR without the amp-list skip first so we could see the build fail and then pass after the fix (see above). @sebastianbenz @juliantoledo PTAL thanks!

**Comment by sebastianbenz** [comment]
We currently duplicate knowledge about the different validation flags across validate-example and compile-example. If we simply attach the metadata object to the file object instead, compile-example no longer needs to know about skipValidation.

**Comment by jkingyens** [comment]
Good idea. Fixed. PTAL thanks!

**Comment by sebastianbenz** [comment]
LGTM

**Pull request merged**
