### PR TITLE
Product sample: Increase height to amp-list

### PR DESCRIPTION
**Pull request by kul3r4**
This fixes the problem where the price is not shown on mobile.

### CODE REVIEW

**Comment by sebastianbenz** [comment]
Shouldn't we remove amp-list and wait for amp-fresh?

**Comment by sebastianbenz** [comment]
otherwise lgtm

**Comment by kul3r4** [comment]
@sebastianbenz PTAL

**Comment by sebastianbenz** [comment]
LGTM

**Pull request merged**
