### PR TITLE
Add initial amp layout sample

### LINKED ISSUE #352: The AMP Layout System

### PR DESCRIPTION
**Pull request by jmadler**
Resolves #352

### CODE REVIEW

**Comment by jmadler** [comment]
Blocked by #355

**Comment by jmadler** [comment]
Made some updates to the sample.

#355 is closed, but https://github.com/ampproject/amphtml/issues/4947 is still blocking this

**Comment by sebastianbenz** [comment]
Would this work better if we wouldn't be using amp-fit-text? I'd like to
get this out as soon as possible as it is super valuable. I might also move
it to the introduction section.

**Comment by jmadler** [comment]
I'm not sure this is a bug in amp-fit-text so much as a bug in the fill layout itself.  It might be possible to omit layout=fill for this round until the other bugs are fixed -- should I try that?

**Comment by sebastianbenz** [comment]
Can you try without amp-fit-text? Maybe I simply didn't understand your
intention.

**Comment by jmadler** [comment]
How would you propose I do this without amp-fit-text?

**Comment by sebastianbenz** [comment]
e.g. use an amp-img. This also makes more sense, as all layouts should work well with images.

**Comment by jmadler** [comment]
This sample uses both amp-img and amp-fit-text.  There are meaningful differences in how text and images resize according to different layout strategies.

I'm unaware of any reason to remove amp-fit-text.  If you're concerned about the display issue, we should cut the layout=fill section or push on the AMP team to fix it.  If you're not, we should move forward.

**Comment by sebastianbenz** [comment]
Reasons why I don't think amp-fit-text is necessary:

* amp-fit-text is rarely used
* amp-fit-text brings it's own semantics which makes things more confusing
* amp-fit-text makes only sense for a limited set of layouts

This sample should be about understanding the different layout types. I think a simple amp-img works well for this use case (container might need a different type though). 

The interesting question is: how can we demonstrate the effect of different viewport sizes on the layout demos? In my experience resizing the browser window works best for understanding the layouts. Can we somehow simulate this?

Sidenote: I removed the fill layout sample, but most demos were still broken.

**Comment by jmadler** [comment]
I don't agree.  The only semantics that amp-fit-text brings is that it applies the layout system to textual content; and while it's true that amp-fit-text only makes sense for a limited set of layouts, and is rarely used,  neither of those facts meaningfully impact its usefulness in this demo.  I think there's still value in demonstrating how text and images respond to different layout types and sizes.  In any event, I'll defer to your judgement here.

In demonstrating different viewport sizes, I'm not sure what the best approach might be.  Does amp-bind allow for some magic here (i.e. buttons that toggle different sizes for an outer container div)?  If not, maybe we can just suggest the user view on different screens.

Yeah, it's possible the bug isn't just with layout=fill -- there's a lot going on here and I haven't really dived into it too deeply.

**Comment by jmadler** [comment]
To clarify: while images can scale in height, width, or both, text is a more fluid content that can change shape to fit its container without concern for its aspect ratio, which is a valid concern from selecting a layout strategy from a UI perspective.

**Comment by sebastianbenz** [comment]
I'd prefer if we leave amp-fit-text out for now. Let's focus on demoing the basic layouts first. We can later add more sophisticated scenarios. 

Awesome idea with amp-bind! You could trigger a css class which scales & animates the container to a larger size.

**Comment by jmadler** [comment]
SGTM.  I'll tweak it later this week.

**Comment by jmadler** [comment]
Added the binding and moved the fill bits over.  PTAL

**Comment by kul3r4** [comment]
@jmadler LGTM but before merging please take a look at the errors from the CI

**Pull request merged**
