### PR TITLE
generate amp viewer previews

### PR DESCRIPTION
**Pull request by sebastianbenz**

### CODE REVIEW

**Comment by sebastianbenz** [comment]
You can preview your AMPs on devices with different screen resolutions:

https://amp-by-example-staging.appspot.com/amp-viewer-device-preview?url=https%3A%2F%2Famp.theguardian.com%2Fscience%2F2016%2Fsep%2F06%2Fnew-drug-wakes-up-immune-system-to-fight-one-of-deadliest-cancers

I think it's pretty useful, but haven't got a clue how to best integrate it into ABE. Have you got any ideas?

@juliantoledo 
@rowan-m 
@pbakaus 
@kul3r4

**Comment by adewale** [comment]
This is pretty cool.
One way to expose the previews might be (on desktop) to offer icons linking to previews for the most common devices next to the "Preview on Github" text.  On mobile the icons could appear next to the Octocat icon.

**Comment by cramforce** [comment]
Neat!

**Comment by sebastianbenz** [comment]
@kul3r4 PTAL

**Comment by sebastianbenz** [comment]
discarding this as it's no longer relevant.

**Pull request closed without merging**
