### PR TITLE
Removes experiment from amp form

### PR DESCRIPTION
**Pull request by kul3r4**

### CODE REVIEW

**Comment by kul3r4** [comment]
@sebastianbenz PTAL

**Comment by sebastianbenz** [comment]
How about the other samples using amp-form?

**Comment by kul3r4** [comment]
You are right! done

**Comment by sebastianbenz** [comment]
What about housing & product_listing?

**Comment by kul3r4** [comment]
Thanks, removed from there as well

**Comment by kul3r4** [comment]
@sebastianbenz In the housing sample, I was using the attribute type for the element li which is obsolete, I added css instead.

**Pull request merged**
