### PR TITLE
Cleanup amp-gist experiment

### PR DESCRIPTION
**Pull request by levidurfee**
Remove experimental meta data for `amp-gist`.

[Cleanup amp-gist experiment](https://github.com/ampproject/amphtml/pull/8652).

### CODE REVIEW

**Comment by sebastianbenz** [comment]
We have to wait until the change has been deployed to prod.

**Comment by levidurfee** [comment]
Thanks! I did jump the gun a little bit :)

**Comment by levidurfee** [comment]
hi @sebastianbenz , can this be merged now that it's live? :)

**Comment by sebastianbenz** [comment]
Validator changes are still not yet live.

**Comment by levidurfee** [comment]
Are the validator changes live?

**Comment by kul3r4** [comment]
@levidurfee Just rerun the CI for this commit and still failing, so it doesn't seem the validator is updated. Could you follow up on [https://github.com/ampproject/amphtml/pull/8652](https://github.com/ampproject/amphtml/pull/8652) if there is anything else that needs to be updated?

**Comment by levidurfee** [comment]
Thanks @kul3r4 ! I'll take another look at it this weekend to see if I missed anything :)

**Pull request closed without merging**
