### PR TITLE
Variables

### PR DESCRIPTION
**Pull request by sebastianbenz**

### CODE REVIEW

**Comment by sebastianbenz** [comment]
@kul3r4 PTAL please also test i didn't break anything (links etc)

**Comment by kul3r4** [comment]
amp-form seems to be broken with this change, can you try it?

**Comment by sebastianbenz** [comment]
Both work fine for me. Did you run the go backend? BTW you can now trigger the go backend via gulp: `gulp backend:watch`

**Comment by sebastianbenz** [comment]
Updated the PR to generate different robots.txt for staging (-> disallow robots) and prod (-> allow robots). 

//cc @jkingyens

**Comment by kul3r4** [comment]
LGTM

**Pull request merged**
